name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa60eeb231741e597a1743800d79ebef0450f9134c414fe8fcb5d6ccd9241f0"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"
