name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d61622fe4cb0daa685a45f6f3abbbd93ddcc55ab62579f73768482901aa86c89"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
