name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98cf2dd3a1a405b7dc6e2b9d4dbcace63654444109c862ad2ef2db5ddef27f7c"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
