name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63240c20b45621e0204ab9ffb0bb3053adce9dd2626734cdee2bb7ae6d406478"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
