name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5876e6d2ac193c03d8d1e55349a9960499cb6721d826a5ac310a78cccb2c0ae5"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
