name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96bb6bef370fe95149a0fe5b2faf12f2f0eb87d8e6083fbb9ec47aef709bc41f"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"
