name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d713cc165d349b81cef6cc1b332d63119e3265cfe9320d6bf55f6b9d229acc68"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
