name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac60fccb3783d8a0b211d66d05fd96b9f946c6dc4af81c401e08d982bbb587fa"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"
