name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a976a177d152aea525a71fdd07874e7d459cb7d718888f387e4eb35a3e191ce"

[versions]
fabric = "0.12.8"
minecraft = "1.18.1"
