name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d686062702e88eb1031b0b299d3dfe0972e7aef44ea9eb295d1ed0c2638ff5c4"

[versions]
fabric = "0.12.11"
minecraft = "1.18.1"
