name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10776422f89ebe7bf05ecba45f5edba958e123b04b153b9649925460f6a0e683"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
