name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "34491508edc207cf6c0040b25da879e560537ac5b42bae814097354d0df0d0ad"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
