name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05eadb3f05ae6df14bd010eca6d44b350bbc5283230ddd60c5b1d20f278b0175"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
