name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9dbfc57fc105097d4e0ba5a434b5885472a14c784ea9a8109d5588ccd8b9735a"

[versions]
fabric = "0.12.8"
minecraft = "1.18.1"
