name = "AH! Real Minecraft"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78e6110c489fd787fd3243bd37f50c2c677dd6fb141bd775b7987a14a04d93b6"

[versions]
fabric = "0.12.8"
minecraft = "1.18"
