name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92c2710233c6be3d6615d133cc6504adc3db17c985f2ba700beba1eb36430cd9"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
