name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1a2858a9a72331a4c88803079a9368aee2313dbaa8e1c53c5902ac6457a0721"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
