name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf2a63a52c78f71e007c5f332f3b766f835dba0c3b7540e92bf5512f4aad5135"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
