name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49bfca78b6b98d0800b323cca9dcb4d12e7f481fa4b401acbefd3600e7a0b9cb"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
