name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ff14a572ee25dd675811205ad9758a55ec77f521b560fefd7e025783c304b7b"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
