name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bfef20a2f036c279c4b53033ffaa26740d1255447bee882dc7a6978ca1203ee"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
