name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6159f5f56891babc21695f138a97ae840155a9a2dfc86cf212698fcc12507071"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
