name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd2f19d73486bcd0b6b9d41743393872ed4792686a9240cd84396d97ffa16bb6"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
