name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "604970518ac52eeb10ebf396737d2b9fd544dfae040543ea37b4beea72d9a455"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
