name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c54131fa6a13558488ec538b4994c4e49125afba215a188a7be1bc5a7684188b"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
