name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39d224af53cfc631ee4de5dcf739acf1ff68ce36d1ba9641774e52fb236dc57a"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
