name = "AHMC-Modpack"
author = "Sloofy"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57c5dbae329f1564294b5c03362abee9ef9293ef16bfae80cbb798cf440a16fe"

[versions]
fabric = "0.12.12"
minecraft = "1.18"
