name = "Consistency+"
filename = "consistency_plus-0.4.2+1.17-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/810/consistency_plus-0.4.2+1.17-fabric.jar"
hash-format = "murmur2"
hash = "1531649896"

[update]
[update.curseforge]
file-id = 3541810
project-id = 430445
