name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18-FABRIC-1.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/947/Croptopia-1.18-FABRIC-1.7.2.jar"
hash-format = "murmur2"
hash = "456256237"

[update]
[update.curseforge]
file-id = 3550947
project-id = 415438
