name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18-FABRIC-1.7.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3549/387/Croptopia-1.18-FABRIC-1.7.1.jar"
hash-format = "murmur2"
hash = "3061017999"

[update]
[update.curseforge]
file-id = 3549387
project-id = 415438
