name = "Fabric Waystones"
filename = "wraith-waystones-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/199/wraith-waystones-2.4.0.jar"
hash-format = "murmur2"
hash = "1004559911"

[update]
[update.curseforge]
file-id = 3575199
project-id = 410902
