name = "Fabric Waystones"
filename = "wraith-waystones-2.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/255/wraith-waystones-2.3.5.jar"
hash-format = "murmur2"
hash = "1837682474"

[update]
[update.curseforge]
file-id = 3569255
project-id = 410902
