name = "Fabric Waystones"
filename = "wraith-waystones-2.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3551/148/wraith-waystones-2.3.2.jar"
hash-format = "murmur2"
hash = "3133741889"

[update]
[update.curseforge]
file-id = 3551148
project-id = 410902
