name = "Krypton"
filename = "krypton-0.1.5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/fQEb0iXm/versions/0.1.5/krypton-0.1.5.jar"
hash-format = "sha512"
hash = "92e78ad9cb9d338001bda4b0c8cc1a75f833951badc7bc7d16cca194ed74f1808227bdceba4f5b20170d16a5086c5d6c193e4446047d0531ad05f0a2c7f3ad71"

[update]
[update.modrinth]
mod-id = "fQEb0iXm"
version = "AXYWaIE8"
