name = "MinecraftCapes Mod"
filename = "MinecraftCapes Fabric 1.18.1-12.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3569/589/MinecraftCapes Fabric 1.18.1-12.0.1.jar"
hash-format = "murmur2"
hash = "1509762741"

[update]
[update.curseforge]
file-id = 3569589
project-id = 359836
