name = "Presence Footsteps"
filename = "PresenceFootsteps-r35-1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3548/844/PresenceFootsteps-r35-1.17.jar"
hash-format = "murmur2"
hash = "3561403638"

[update]
[update.curseforge]
file-id = 3548844
project-id = 334259
