name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.1.22.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3557/160/voicechat-fabric-1.18.1-2.1.22.jar"
hash-format = "murmur2"
hash = "2495609214"

[update]
[update.curseforge]
file-id = 3557160
project-id = 416089
