name = "FabricSit"
filename = "FabricSit-1.7.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/eM1KzRjc/versions/1.7.0/FabricSit-1.7.0.jar"
hash-format = "sha512"
hash = "a212184cb3983a622a2bdf907454605f96d2c4eea52aab5aa3eb5abcf886cd65c17530124415ad4884d1a83faac38ec3f1949165ac5286ce333b1803d92f5e1c"

[update]
[update.modrinth]
mod-id = "eM1KzRjc"
version = "RTR6qRRp"
