name = "Vanessence"
filename = "vanilla-essence-3.0.0-1.18.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/aGWV9KmJ/versions/3.0.0-1.18/vanilla-essence-3.0.0-1.18.jar"
hash-format = "sha512"
hash = "51123f0fd2b81bafcbdbe375685fda9613e7091aceab7bef7990f5e65facb35f072fbcbf8a22fa79baeafc24bcaa08c1fa388ceeb8e253431bf09c2e0f6378d7"

[update]
[update.modrinth]
mod-id = "aGWV9KmJ"
version = "XVo40Zax"
