name = "Villager Names (Fabric)"
filename = "villagernames-1.18-2.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3550/878/villagernames-1.18-2.0.2.jar"
hash-format = "murmur2"
hash = "3858960898"

[update]
[update.curseforge]
file-id = 3550878
project-id = 416379
